### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [ikalnytskyi/picobox#58]
Is it possible next time on release new version make the github release to have entry on https://github.com/ikalnytskyi/picobox/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by ikalnytskyi** [comment]
Thanks for the suggestion!

I also find subscribing for releases is awesome feature to have. I'll do GitHub Releases from now on. I also plan to create releases for previously created tags, so I hope it won't break your automation.

**Comment by kloczek** [comment]
This PR is fresh and may be useful for you https://github.com/jbms/sphinx-immaterial/pull/282

**Comment by kloczek** [comment]
Just noticed that my automation was able successfully process new gh release email producing automatically new rpm package.
Thank you 👍 😄
