### ISSUE TITLE
3.0.0: module documentation build still uses bits from `setuptools`

### ISSUE THREAD

**Issue by kloczek** [ikalnytskyi/picobox#59]
Despite move pep517 backend from `setuptools` to `hatchling` documentation build still uses `pkg_resources` which is part of the `setuptools` and arendy is marked as deprecated.
https://importlib-resources.readthedocs.io/en/latest/migration.html

**Comment by ikalnytskyi** [comment]
Thank you for the report. I just recently learned about `importlib.metadata` and `pkg_resources` deprecation. Apparently `pkg_resources` is not even a thing on Python 3.12 (the docs job failed).

It should be fixed now by https://github.com/ikalnytskyi/picobox/pull/61.
